base:
  random_seed: 42
data:
  exist:
      task_one:
        raw: path/to/raw.csv
        preprocessed: path/to/preprocessed.csv
        augmented: path/to/augmented.csv
  csmb:
    raw: path/to/raw.csv
    processed: path/to/processed.csv
base_model:
  model_arch: path/to/hugging_face/models
trained_models:
  exist:
    task_one:
      model_dir: path/to/model
  csmb:
    model_dir: path/to/model
reports:
  metrics: /path/to/save/metrics.json
  loss_plot: /path/to/save/loss_curves.png
  logs: /path/to/save/logs.log
