base:
  random_seed: 31
data:
  train:
    exist:
      raw: data/raw/exist/EXIST2021_training.tsv
      preprocessed: data/preprocessed/exist/EXIST2021_training_preprocessed.csv
      augmented: data/augmented/exist/EXIST2021_training_augmented.csv
      aug_preprocessed: data/augmented/exist/EXIST2021_training_augmented_preprocessed.csv
    csmb:
      original: data/raw/csmb/sexism_data.csv
      raw: data/raw/csmb/sexism_train_data.csv
      preprocessed: data/preprocessed/csmb/sexism_test_data.csv
  test:
    exist:
      raw: data/raw/exist/EXIST2021_test_labeled.tsv
      preprocessed: data/preprocessed/exist/EXIST2021_test_preprocessed.csv
    csmb:
      raw: data/raw/csmb/sexism_data_test.csv
      preprocessed: data/preprocessed/csmb/sexism_data_preprocessed_test.csv

base_model:
  distil_bert: 
    model: distilbert-base-uncased
    hyper_params:
      batch_size: 16
      epochs: 5
      lr: 2e-5
      wt_deacy: 0.01

# trained_models:
#   exist:
#     task_one:
#       model_dir: path/to/model
#   csmb:
#     model_dir: path/to/model
# reports:
#   metrics: /path/to/save/metrics.json
#   loss_plot: /path/to/save/loss_curves.png
#   logs: /path/to/save/logs.log
class_label:
  task1:
  - non-sexist
  - sexist
  task2:
  - ideological-inequality
  - misogyny-non-sexual-violence
  - non-sexist
  - objectification
  - sexual-violence
  - stereotyping-dominance
  csmb:
  - 'False'
  - 'True'
